home:
    path: /
    controller: App\Controller\PageController:home
    methods: get

about:
    path: /about
    controller: App\Controller\PageController:about
    methods: get

list:
    path: /list
    controller: App\Controller\SongController:list
    methods: get

song:
    path: /song/{id}
    controller: App\Controller\SongController:song
    methods: get

script:
    path: /script
    controller: App\Controller\SongController:songCreatorScript