home:
    path: /
    controller: App\Controller\PageController:home
    methods: get

list:
    path: /list
    controller: App\Controller\PageController:list
    methods: get

song:
    path: /song/{id}
    controller: App\Controller\PageController:song
    methods: get

script:
    path: /script
    controller: App\Controller\PageController:songCreatorScript